dist: trusty

language: rust
rust:
- nightly

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

install:
    - cargo install mdbook || true

script:
    - true

before_deploy:
    - mdbook build

deploy:
  local_dir: book
  repo: swc-project/swc-project.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  email: kdy1@outlook.kr
  name: "강동윤"
  on:
    branch: master

notifications:
  email: never

branches:
  only:
    - master
